# Generated by Django 3.2.5 on 2021-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="background",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
