# Generated by Django 3.2.5 on 2021-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_restaurant_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
