# Generated by Django 3.2.5 on 2021-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_restaurant_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="background",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.CharField(max_length=400),
        ),
    ]
