# Generated by Django 3.2.5 on 2021-07-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_auto_20210719_1232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="background",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.ImageField(null=True, upload_to="bg"),
        ),
    ]
