# Generated by Django 3.2.5 on 2021-07-27 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0007_auto_20210720_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.JSONField()),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('region_address', models.CharField(max_length=128)),
                ('city_address', models.CharField(max_length=128)),
                ('street_address', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=5)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
