# Generated by Django 3.2.5 on 2021-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dishes",
            field=models.JSONField(null=True),
        ),
    ]
