# Generated by Django 3.2.5 on 2021-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0010_auto_20210728_0601"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
