# Generated by Django 3.2.5 on 2021-07-28 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0011_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(2)]
            ),
        ),
    ]
